#!/usr/bin/env bash
# Transfers a file from our client to a server; accepts 4 parameters
# Before running this script, we will run this to list server's existing content
#  	 ssh ubuntu@35.229.54.225 -i ~/.ssh/holberton 'ls ~/'
#	 touch newfile.html
# After running script, we will run this to check new content is transferred to server
#	 ssh ubuntu@35.229.54.225 -i ~/.ssh/holberton 'ls ~/
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
