#!/usr/bin/env bash
# Show a message in 404 error
sudo apt-get update -y
sudo apt-get install nginx -y

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.nginx-debian.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

first_line="server_name _;\n\trewrite ^\/redirect_me youtube.com permanent;"
second_line="\n\tadd_header X-Served-By \$hostname;"
third_line="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$first_line$second_line$third_line/" /etc/nginx/sites-enabled/default
service nginx start
