#!/usr/bin/env bash
# Installs, configures, and starts the web server

apt-get update
apt-get -y install nginx

mkdir -p /var/www/html /var/www/error
touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
touch /var/www/error/404.html
echo -e "Ceci n'est pas une page" > /var/www/error/404.html

# Server's configuration
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
		add_header X-Served-By \$hostname;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=rSn_X_Em6Vo permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		root /var/www/error/;
		internal;
		add_header X-Served-By \$hostname;
	}
}"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
