#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
host=$(hostname)
nl="\\\tadd_header X-Served-By \"$host";"
sudo sed -i -e "/sendfile/i $nl" /etc/nginx/nginx.conf
sudo service nginx restart
