#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely
# Note that | ctrl+c (killed) the Bash script
# Author: Waython Yesse

while true
do
    echo "To infinity and beyond"
    sleep 2
done
