#!/usr/bin/env bash
#This script displays:
# - The content of the current directory
# - In a list format
# - Where only the part of the name after the first dash is displayed
# Author: Waython Yesse

files="$(ls)"
for f in $files;
do
    echo "$f" | cut -d "-" -f2
done
